In [1]:
# AND
import numpy as np
import math

x = np.array([[1,1,1], [1,1,-1], [1,-1,1], [1,-1,-1], [-1,1,1], [-1,1,-1], [-1,-1,1], [-1,-1,-1]])
r = np.array([1,-1, 1, -1, 1, -1, 1, 1])
w = [0,0,0,0]
b = 0
coAlpha = 0.1
wrong = True

print("Initial weight: ", w)

counter = 0

while(wrong):
    counter += 1
    wrong = True
    diff = [0,0,0,0]
    for i in range(len(x)):
        y_in = w[3] + (w[0]*x[i][0] + w[1]*x[i][1] + w[2]*x[i][2])
        update = coAlpha * (r[i] - y_in)
        b = b + update
        w[:3] += coAlpha * (r[i] - y_in) * x[i]
        w[3] += update
        print(x[i], ": ", r[i], ": ", y_in, ": ", w[1:], " ", w[3], "\n")
    
    if(counter == 1):
        wrong = False
        
print("\nFinal weight found in ", counter, " iteration\nFinal weight : ", w)

Initial weight:  [0, 0, 0, 0]
[1 1 1] :  1 :  0 :  [0.10000000000000001, 0.10000000000000001, 0.10000000000000001]   0.1 

[ 1  1 -1] :  -1 :  0.2 :  [-0.01999999999999999, 0.22, -0.01999999999999999]   -0.02 

[ 1 -1  1] :  1 :  0.2 :  [-0.10000000000000001, 0.30000000000000004, 0.060000000000000026]   0.06 

[ 1 -1 -1] :  -1 :  -0.08 :  [-0.0079999999999999932, 0.39200000000000007, -0.031999999999999987]   -0.032 

[-1  1  1] :  1 :  0.384 :  [0.053599999999999995, 0.45360000000000006, 0.029600000000000001]   0.0296 

[-1  1 -1] :  -1 :  -0.2768 :  [-0.018719999999999987, 0.52592000000000005, -0.04271999999999998]   -0.04272 

[-1 -1  1] :  1 :  0.5232 :  [-0.066399999999999987, 0.57360000000000011, 0.0049600000000000199]   0.00496 

[-1 -1 -1] :  1 :  -0.43328 :  [-0.209728, 0.4302720000000001, 0.14828800000000003]   0.148288 


Final weight found in  1  iteration
Final weight :  [-0.212288, -0.209728, 0.4302720000000001, 0.14828800000000003]
